development:
  adapter: postgresql
  encoding: unicode
  database: ember-crm-offical_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: ember-crm-official_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: ember-crm-official_production
  pool: 5
